-- CreateTable
CREATE TABLE "REFRESH_TOKENS" (
    "id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "REFRESH_TOKENS_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "REFRESH_TOKENS_token_key" ON "REFRESH_TOKENS"("token");

-- AddForeignKey
ALTER TABLE "REFRESH_TOKENS" ADD CONSTRAINT "REFRESH_TOKENS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("username") ON DELETE CASCADE ON UPDATE CASCADE;
